School/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import LoginView, SignupView, ForgottenView, LogoutView, ExploreView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('registro/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password-reset/', ForgottenView.as_view(), name="reset" ),
    path('explore/', ExploreView.as_view(), name="exploring"),
    path('profesores/', include('profesores.urls', namespace='teachers-place')),
    path('estudiantes/', include('estudiantes.urls', namespace='students-place')),
    path('api-side/', include('apiPart.urls', namespace='api')),
    path('admin/', admin.site.urls),
  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

estudiantes/urls.py
from django.urls import path
from estudiantes.views import *
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'estudiantes'

urlpatterns = [
    path('', HomeView.as_view(), name="students-home"),
    path('mensajes/', MessageView.as_view(), name="messages"),
    path('desktop/',  Desktopview.as_view(), name="desktop"),
    path('perfil/',  PerfilView.as_view(), name='public'),
    path('friends/', FriendsView.as_view(), name='amigos'),
    path('settings/', SettingsView.as_view(), name='configurations')

]

profesores/urls.py
from django.urls import path
from . views import *
from . import views

app_name = 'profesores'

urlpatterns = [
    path('', HomeView.as_view(), name='teachers_home'),
    path('desktop/', DeskView.as_view(), name='desktop'),
    path('mensajes/', MessagesView.as_view(), name='teachers_messages'),
    path('perfil/', PerfilView.as_view(), name='teacher_perfil'),
    path('friends/', FriendsView.as_view(), name='co-workers'),
    path('Live/', LiveView.as_view(), name='homework'),
]

estudiantes/models.py
from django.db import models
from django.db.models.fields import DateField
from django.utils import timezone
from principal.models import User_data

# Create your models here.

class Courses(models.Model):
      name = models.CharField(max_length=90, primary_key=True)


class homework_s(models.Model):
      addresses = models.CharField(max_length= 90, primary_key=True)
      descriptions = models.CharField(max_length=200)
      homework_file = models.FileField(upload_to='home_work_files/')
      Date = models.DateField(auto_now=True)
      users = models.ForeignKey(User_data, on_delete=models.CASCADE)

class Posts(models.Model):
      content = models.CharField(max_length=100, primary_key=True)
      fecha = models.DateField(auto_now=True)
      hora_post = models.TimeField(auto_now=True)
      post_img = models.ImageField(upload_to='TComentImg/')
      users = models.ForeignKey(User_data, on_delete=models.CASCADE)


class message_data(models.Model):
    receiver = models.CharField(max_length=100, primary_key=True)
    asunto = models.CharField(max_length=90)
    content = models.TextField()
    users = models.ForeignKey(User_data, on_delete=models.CASCADE)


class Friends(models.Model):
      name = models.CharField(max_length=90, primary_key=True)
      courses = models.CharField(max_length=90)
      users = models.ForeignKey(User_data, on_delete=models.CASCADE)

estudiantes/forms.py
import datetime
from django import forms
from django.forms import widgets, ModelForm, Textarea
from django.utils.translation import gettext_lazy as _
from estudiantes.models import *


class Tareas(ModelForm):
     class Meta:
          model = homework_s
          fields = "__all__"
          labels = {
            'title': _('')
          }
          exclude = ['users']
          widgets = {
            'descriptions': Textarea(attrs={'cols': 40, 'rows': 10}),
            'title':forms.TextInput(attrs={"placeholder": "Titulo de la Tarea: "}),
          }


     def clean(self):
           cleaned_data = super(Tareas, self).clean()
           self.title = cleaned_data.get("title")
           self.description = cleaned_data.get("description")
           self.homework_file = cleaned_data.get("homework_file")
           self.Date = cleaned_data.get("Date")
           self.teachers_comments = cleaned_data.get("Email")

           return cleaned_data

class SearchForm(forms.Form):
     searchfield = forms.CharField(max_length=90, widget=forms.TextInput(attrs={'placeholder': 'Search'}), label='')


class Message_form(ModelForm):
      class Meta:
          model = message_data
          fields = ['receiver', 'asunto', 'content']
          exclude = ['users']
          labels = {
            'receiver': _(''),
            'asunto': _(''),
            'content': _(''),
          }
          widgets = {
            'receiver':forms.TextInput(attrs={"placeholder": "Para:"}),
             'asunto':forms.TextInput(attrs={"placeholder": "asunto:"}),
            'content': Textarea(attrs={'cols': 60, 'rows': 20}),
          }

      def clean(self):
           cleaned_data = super(Message_form, self).clean()
           self.receiver = cleaned_data.get("receiver")
           self.asunto = cleaned_data.get("asunto")
           self.content = cleaned_data.get("content")
           self.users = cleaned_data.get("users")
           return cleaned_data

estudiantes/views.py
from django.shortcuts import render
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateResponseMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from  .forms import *
from rest_framework import viewsets
from .models import *
from rest_framework import permissions
import os


# Create your views here.

class HomeView(ListView):
    template_name = 'home-student.html'
    form_class = [SearchForm, Posts, ]
    model = Posts
    object_list = Posts.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form1'] = self.form_class[0]()
        context['form2'] = self.form_class[1]()
        return context

    def get(self, request, *args, **kwags):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        form1 = context['form1']
        form2 = context['form2']
        if form1.is_valid():
            print('form1 is valid')
        else:
            print('form1 not valid')
        if  form2.is_valid():
           new_post = PostContent(
               content = form2.content,
               fecha = form2.fecha,
               hora_post = form2.hora_post,
           )

           print('esto es un post', new_post.content, 'esto es la hora', new_post.hora_post)

        else:
            print('form2 is not valid')
        return render(request, self.template_name,context)




class PerfilView(View):
    form_class = {
        'form1': homework_s,
    }
    template_name = "student_perfil.html"


    def get(self, request, *args, **kwargs):
         forms = {
          'form1': self.form_class['form1'](),

         }

         return render(request, self.template_name, {'forms':forms})

    def post(self, request, *args, **kwargs):
        forms = {
          'form1': self.form_class['form1'](),

        }

        return render(request, self.template_name, {'forms':forms})

class MessageView(View):
    form_class = Message_form
    template_name = 'm_estudiantes.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
           user_id = request.user
           mssg = message_data(
              receiver = form.receiver,
              asunto = form.asunto,
              content = form.content,
              users = request.user
           )

           mssg.save()
           print("mierda ")
        return render(request, self.template_name, {'form':form})

class Desktopview(View):
     form_class = Tareas
     template_name = "workshop_student.html"

     def get(self, request, *args, **kwargs):
          form = self.form_class()
          return render(request, self.template_name, {'form':form})

     def post(self, request, *args, **kwargs):
         form = self.form(request.POST, request.FILES)
         if form.is_valid():
           print('mierda')
         return render(request, self.template_name, {'form':form})



class SettingsView(View):
     template_name = "settings.html"

     def get(self, request, *args, **kwargs):
         return render(request, self.template_name)


class FriendsView(View):
     template_name = "friends.html"

     def get(self, request, *args, **kwargs):
         return render(request, self.template_name)

estudiantes/templates/base/base_friends.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/friends.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@300&display=swap" rel="stylesheet">

    <title>Document</title>
</head>
<body>
    <div id="general_box">
        {% include 'base/header.html' %}
        {% block friends %} {% endblock %}
    </div>
</body>
</html>

estudiantes/templates/base/base_home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'javascript/proccessFile.js' %}"></script>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/perfil.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--otherfont-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@1,300;1,500&display=swap" rel="stylesheet">

    <title>Document</title>
</head>
<body>
   <div id="general_box">
     <header>
        <h1 id="title">TutorLink</h1>
        <div id="search_block">
           <form method="POST" id="search_form">
                {% csrf_token %}
                <button id="search_btn">
                  <span class="material-symbols-outlined">search</span>
                 </button>
                 {{ form1.searchfield }}
           </form>
        </div>
        <div id="picture" onclick="effect1()"></div>
     </header>
     <div id="root_content">
           <section id="left_column">
               <ul id="menu_feature">
                  <li class="parts">
                     <a href="{% url  'estudiantes:students-home'%}" class="hyperlink"> <span class="material-symbols-sharp">home</span>Inicio</a>
                  </li>
                  <li class="parts">
                     <a href="{% url 'estudiantes:messages' %}" class="hyperlink"> <span class="material-symbols-sharp">chat</span>messages</a>
                  </li>
                  <li class="parts">
                     <a href="{% url 'estudiantes:desktop' %}" class="hyperlink"><span class="material-symbols-sharp">work</span>workshop</a>
                  </li>
                  <li class="parts">
                     <a href="{% url 'estudiantes:desktop' %}" class="hyperlink"><span class="material-symbols-sharp">explore</span>Explore</a>
                  </li>


                  <li class="parts">
                     <a href="{% url  'profesores:co-workers' %}" class="hyperlink"><span class="material-symbols-sharp">group</span>Friends</a>
                  </li>
                  <li class="parts">

                     <p class="hyperlink"><span class="material-symbols-sharp">notifications</span>Notificaciones</p>
                  </li>
                  <li class="parts">
                     <a href="{% url 'profesores:teacher_perfil' %}" class="hyperlink"><span class="material-symbols-sharp">person</span>Perfil</a>
                  </li>
                  <li class="parts" onclick="menu_hidden">
                     <p class="hyperlink"> <span class="material-symbols-sharp">more_vert</span>Mas</a>
                  </li>
               </ul>
            </section>
            <main id="block_content">
               {% if user.is_authenticated %}
                  {% if not User_data.image_field %}
                    <div id="image-card">
                        <div id="image_btn">
                             <img src="{% static 'images/notuser3.png' %}" alt="notuseratall" id="notuserbtn">
                        </div>
                        <div id="id_mssg">
                           <h2 id="mssg1">Agrega una imagen tuya</h2>
                           <p id="mssg2">Añade una foto para que tus amigos puedan identificarte fácilmente.</p>

                        </div>
                        <input type="button" value="Upload" id="load-btn">
                    </div>
                  {% else %}
                    <div id="hiddencont">

                    </div>
                  {% endif %}
                  <div id="personal_coment">
                     <div id="user_content">
                         {% if not User_data.image_field %}
                              <div id="img-data">
                                 <img src="{% static 'images/notuser3.png' %}" alt="notuser">
                              </div>
                         {% else %}
                              <div id="img-data">
                                  <p>image campeon</p>
                              </div>
                         {% endif %}
                       <button id="new_post" id="public" onclick="newPost()">
                             <span>Crea una publicacion...</span>
                       </button>
                     </div>
                   <div id="uploadedTools">
                       <ul id="upload-tools">
                           <li class="files">
                              <span class="material-symbols-outlined" id="icon1">upload_file</span>
                           </li>
                           <li class="files">
                              <span class="material-symbols-outlined">image</span>
                           </li>
                           <li class="files">
                              <span class="material-symbols-outlined">slideshow</span>
                           </li>
                           <li class="files">
                              <span class="material-symbols-outlined">schedule</span>
                           </li>
                       </ul>
                   </div>
                </div>
                {{ form2.non_field_errors }}
                <div id="ads">
                    <ul id="hidden-boxes">
                       <li class="boxes">

                       </li>
                    </ul>
                </div>
                {% else %}
                   <div id="adding-img">
                      <p id="login-necessary">log in to enjoy our plattaform </p>
                   </div>
                {% endif %}
            </main>
            <section id="right_column">
               <ul id="recomended_menu">
                  <li id="anounce" class="reco">
                     <p id="recomends"></p>Cursos Recomendados</p>
                  </li>
                  <li id="re2" class="reco">
                     <p class="recomends">secound_option</p>
                  </li>
                  <li id="re3" class="reco">
                     <p class="recomends">thrid_option</p>
                  </li>
                  <li id="re4" class="reco">
                     <p class="recomends">four_option</p>
                  </li>
                  <li id="re5" class="reco">
                     <p class="recomends">five_option</p>
                  </li>
               </ul>
           </section>
      <div id="publish">
           <form action="" method="post" id="coment_form">
                <div id="label-box">
                    <h2 id="coment_title">Crear una publicacion:</h2>
                    <span class="material-symbols-outlined" id="close_comment" onclick="closingTab()">close</span>
                </div>
                {% if user.is_authenticated %}
                {% csrf_token %}
                 <div id="form-part1">
                     <div id="user-picture">

                     </div>
                     <div id="user-data">
                         <p id="username-data">{{ user.username }}</p>
                         <select name="user-type" id="type">
                             <option value="option1">Public</option>
                             <option value="option2">Friends</option>
                         </select>
                     </div>
                 </div>
                 {{ form2.content }}
                 <div id="post-tools">
                     <span class="material-symbols-outlined" id="icon-tool1">image</span>
                     <span class="material-symbols-outlined" id="icon-tool2">video_library</span>
                     <span class="material-symbols-outlined" id="icon-tool3">article</span>
                     <span class="material-symbols-outlined"id="icon-tool4">schedule</span>
                 </div>
                 <div id="picture-part">

                 </div>
                 <div id="video-part">

                 </div>
                 <input type="submit" value="cargar" id="upload-coment">
                 {% else %}
                    <p id="not-usermssg">
                       login to make a post
                    </p>
                  {% endif %}
           </form>
      </div>


      <div id="accounts_manager">
           <div id="account_data">
               <div id="picture_account">

               </div>
               <h3>{{ user.username }}</h3>
               <h3>{{user.email}}</h3>
           </div>
           <div id="accounts">
               {% if user.is_authenticated %}
                 <a href="#" class="manager">Log-out</a>
                 {% else %}
                 <a href="#" class="manager">Log-In</a>
               {% endif %}
               <a href="" id="change_account" class="manager">Cambiar cuenta</a>
               <a href="" id="salir" class="manager">Salir de todas las cuentas</a>
            </div>
      </div>
      <div id="more_block">
         <ul id="settings">
            <li class="configurations" id="conf">
               <a href="{% url 'estudiantes:configurations' %}" class="set_configuration">Configuracion</a>
            </li>
            <li class="configurations" id="saved">
               <a href="" class="set_configuration">Guardadas</a>
            </li>
            <li class="configurations" id="activity">
               <a href="" class="set_configuration">Tu actividad</a>
            </li>
            <li class="configurations" id="problem">
               <a href="" class="set_configuration">Informar de un problema</a>
            </li>
            <li class="configurations" id="changelook" onclick="Night()">
              <p class="set_configuration">Cambiar Aspecto</p>
            </li>
         </ul>
      </div>
      <form method="POST" name="img-form" id="img-load">
         <span class="material-symbols-sharp" id="close_img">close</span>
           {% csrf_token %}
           {{ ImageLoad }}
      </form>

   </div>
</body>
</html>

estudiantes/templates/base/base_public.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="{% static 'javascript/t_effect.js' %}"></script>
    <title>Document</title>
</head>
<body>
    <div id="general_box">
      <header>
         <h1 id="title">Educocity</h1>
         <div id="picture"></div>
         <div id="search_block">
            <form method="POST" id="search_form">
                 {% csrf_token %}
                 <button id="search_btn">
                    <span class="material-symbols-outlined">search</span>
                 </button>
                 <input type="search" name="searcher" id="search_field" placeholder="Buscar">
            </form>
         </div>
      </header>
      <div id="root_content">
         <div id="left_column">
            <ul id="menu_feature">
               <li class="parts">
                  <a href="{% url  'estudiantes:students-home'%}" class="hyperlink"> <span class="material-symbols-sharp">home</span>Inicio</a>
               </li>
               <li class="parts">
                  <a href="{% url 'profesores:teachers_messages' %}" class="hyperlink"> <span class="material-symbols-sharp">chat</span>messages</a>
               </li>
               <li class="parts">
                  <a href="{% url 'profesores:desktop' %}" class="hyperlink"><span class="material-symbols-sharp">work</span>workshop</a>
               </li>

               <li class="parts">
                  <a href="{% url  'profesores:co-workers' %}" class="hyperlink"><span class="material-symbols-sharp">group</span>Friends</a>
               </li>
               <li class="parts">

                  <p class="hyperlink"><span class="material-symbols-sharp">notifications</span>Notificaciones</p>
               </li>
               <li class="parts">
                  <a href="{% url 'profesores:teacher_perfil' %}" class="hyperlink"><span class="material-symbols-sharp">person</span>Perfil</a>
               </li>
               <li class="parts" onclick="menu_hidden">
                  <p class="hyperlink"> <span class="material-symbols-sharp">more_vert</span>Mas</a>
               </li>
            </ul>
        </div>
            <div id="data">
                <div id="user_block">
                   {% block user_data %} {% endblock %}
                </div>
                <div id="user_content">
                   <ul id="user_data">
                      <li class="data_info">
                         <p class="info">Tareas</p>
                      </li>
                      <li class="data_info">
                         <p class="info">Examenes</p>
                      </li>
                      <li class="data_info">
                         <p class="info">Notas</p>
                      </li>
                   </ul>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

estudiantes/templates/base/base_settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <div id="general_box">
      <header>
          <h1>School</h1>
      </header>
      <div id="root_content">
         
      </div>
  </div>
</body>
</html>

estudiantes/templates/base/config1.html
<div id="more_block">
    <ul id="settings">
        <li class="configurations" id="conf">
           <a href="{% url 'estudiantes:configurations' %}" class="set_configuration">Configuracion</a>
        </li>
        <li class="configurations" id="saved">
           <a href="" class="set_configuration">Guardadas</a>
        </li>
        <li class="configurations" id="activity">
           <a href="" class="set_configuration">Tu actividad</a>
        </li>
        <li class="configurations" id="problem">
           <a href="" class="set_configuration">Informar de un problema</a>
        </li>
        <li class="configurations" id="changelook" onclick="Night()">
           <p class="set_configuration">Cambiar Aspecto</p>
        </li>
    </ul>
 </div>

estudiantes/templates/base/header.html
   {% load static %}
    <header>
       <link rel="stylesheet" href="{% static 'css/header.css' %}">
       <link rel="preconnect" href="https://fonts.googleapis.com">
       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
       <!---icons -->
       <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
       <!--icons-->
       <script src="{% static 'javascript/desk.js' %}"></script>
       <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@300&display=swap" rel="stylesheet">
       <h1 id="title">Educocity</h1>
       <div id="picture"></div> 
       <div id="search_block">
          <form method="POST" id="search_form">
               {% csrf_token %}
               <button id="search_btn">
                  <span class="material-symbols-outlined">search</span>
               </button>
               <input type="search" name="searcher" id="search_field" placeholder="Buscar">
          </form>
       </div>
    </header>

estudiantes/templates/base/left_column.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/lcolumn.css' %}">
    <!--icons-->
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <title>Document</title>
</head>
<div id="left_column">
    <ul id="menu_feature">
       <li class="parts">
          <a href="{% url  'estudiantes:home'%}" class="hyperlink"> <span class="material-symbols-sharp">home</span>Inicio</a>
       </li>
       <li class="parts">
          <a href="{% url 'estudiantes:messages' %}" class="hyperlink"> <span class="material-symbols-sharp">chat</span>messages</a>
       </li>
       <li class="parts">
          <a href="{% url 'estudiantes:desktop' %}" class="hyperlink"><span class="material-symbols-sharp">work</span>workshop</a>
       </li>
    
       <li class="parts">
          <a href="{% url  'estudiantes:amigos' %}" class="hyperlink"><span class="material-symbols-sharp">group</span>Friends</a>
       </li>
       <li class="parts">
          
          <p class="hyperlink"><span class="material-symbols-sharp">notifications</span>Notificaciones</p>
       </li>
       <li class="parts">                           
          <a href="{% url 'estudiantes:public' %}" class="hyperlink"><span class="material-symbols-sharp">person</span>Perfil</a>
       </li>
       <li class="parts" onclick="menu_hidden">
          <p class="hyperlink"> <span class="material-symbols-sharp">more_vert</span>Mas</a>
       </li>
    </ul>
</div>

estudiantes/templates/base/right-column.html
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/rightColumn.css' %}">
    <title>Document</title>
</head>
<div id="right_column">
    <div id="sec_feature">
        <ul id="sec_menu">
          <li class="homework_tools" id="new_file">
             <button id="btn1" class="btns">
                <p class="objects">Redactar</p>
             </button>
          </li>
          <li id="courses" class="homework_tools">
             <button id="btn1" class="btns">
               <p class="objects">Tus-Cursos</p>
             </button>
          </li>
        </ul>
    </div>
</div>
<div id="courses_container">
    <button id="new-course"><span>New Course</span></button>
    Esto es para los cursos
</div>

estudiantes/templates/base/right_column.html
{% load static %}
<div id="right_column">
    <link rel="stylesheet" href="{% static 'css/RColumn.css' %}">
    <div id="sec_feature">
       <ul id="recomended_menu">
          <li id="anounce" class="reco">
             <p id="recomended"></p>Cursos Recomendados</p>
          </li>
          <li id="re2" class="reco">
             <p class="recomends">secound_option</p>
          </li>
          <li id="re3" class="reco">
             <p class="recomends">thrid_option</p>
          </li>
          <li id="re4" class="reco">
             <p class="recomends">four_option</p>
          </li>
          <li id="re5" class="reco">
             <p class="recomends">five_option</p>
          </li>
       </ul>
    </div>
</div>