School/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import LoginView, SignupView, ForgottenView, LogoutView, ExploreView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('registro/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password-reset/', ForgottenView.as_view(), name="reset" ),
    path('explore/', ExploreView.as_view(), name="exploring"),
    path('profesores/', include('profesores.urls', namespace='teachers-place')),
    path('estudiantes/', include('estudiantes.urls', namespace='students-place')),
    path('api-side/', include('apiPart.urls', namespace='api')),
    path('admin/', admin.site.urls),
  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

estudiantes/urls.py
from django.urls import path
from estudiantes.views import *
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'estudiantes'

urlpatterns = [
    path('', HomeView.as_view(), name="students-home"),
    path('mensajes/', MessageView.as_view(), name="messages"),
    path('desktop/',  Desktopview.as_view(), name="desktop"),
    path('perfil/',  PerfilView.as_view(), name='public'),
    path('friends/', FriendsView.as_view(), name='amigos'),
    path('settings/', SettingsView.as_view(), name='configurations')

]

profesores/urls.py
from django.urls import path
from . views import *
from . import views

app_name = 'profesores'

urlpatterns = [
    path('', HomeView.as_view(), name='teachers_home'),
    path('desktop/', DeskView.as_view(), name='desktop'),
    path('mensajes/', MessagesView.as_view(), name='teachers_messages'),
    path('perfil/', PerfilView.as_view(), name='teacher_perfil'),
    path('friends/', FriendsView.as_view(), name='co-workers'),
    path('Live/', LiveView.as_view(), name='homework'),
]

profesores/models.py
from django.db import models
from django.forms.fields import DateField
from principal.models import User_data


# Create your models here.

class Courses(models.Model):
      courses_name = models.CharField(max_length=90, primary_key=True)
      courses_description = models.CharField(max_length=300)
      miniatura = models.ImageField()
      hora_ini = models.TimeField()
      hora_fin = models.TimeField()
      users = models.ForeignKey(User_data, on_delete=models.CASCADE)



class Teachers_homework(models.Model):
     homework_title = models.CharField(max_length=100, primary_key=True)
     homework_description = models.CharField(max_length=200)
     first_question = models.CharField(max_length=110)
     secound_question = models.CharField(max_length=110)
     third_question = models.CharField(max_length=110)
     fourth_question = models.CharField(max_length=110)
     fifth_question = models.CharField(max_length=110)
     form_type = models.CharField(max_length=7, choices=[('form1', 'form-type1'), ('form2', 'form-type2'), ('form3', 'form-type3'), ('form4', 'form-type4'), ('form5', 'form-type5')])
     font_size = models.CharField(max_length=20, choices=[ ('font-size1', '10%'), ('font-size2', '20%'), ('font-size3', '40%'), ('font-size4', '60%'), ('font-size5', '80%'), ('font-size6', '100%'),])
     users = models.ForeignKey(User_data, on_delete=models.CASCADE)


class Teachers_message(models.Model):
      receiver = models.CharField(max_length=100, primary_key=True)
      asunto = models.CharField(max_length=90)
      content = models.TextField()
      users = models.ForeignKey(User_data, on_delete=models.CASCADE)



class PostContent(models.Model):
      content = models.CharField(max_length=100, primary_key=True)
      fecha = models.DateField(auto_now=True)
      hora_post = models.TimeField(auto_now=True)
      post_img = models.ImageField(upload_to='TComentImg/')
      users = models.ForeignKey(User_data, on_delete=models.CASCADE)

class Lessons(models.Model):
      title = models.CharField(max_length=90, primary_key=True)
      description = models.CharField(max_length=200)
      lesson_file = models.FileField()

profesores/forms.py
from django import forms
from django.forms.widgets import Textarea
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from .models import *
from principal.models import User_data
import datetime
from django.core.exceptions import ValidationError

     

class ImageLoad(ModelForm):
    class Meta:
        model = User_data
        fields = ['image_field']
     
    def clean(self):
       cleaned_data = super(ImageLoad, self).clean() 
       self.image_field = cleaned_data.get("image_field")    

class NewCoursesform(ModelForm):
     class Meta:
          model = Courses
          fields = "__all__"
          exclude = ['users']
          widgets = {
            'courses_name':forms.TextInput(attrs={"placeholder": "Nombre del Curso: "}),
            'courses_description': Textarea(attrs={'cols': 66, 'rows': 10, 'placeholder': 'Enter a description here...'}),
            'hora_ini':forms.TextInput(attrs={"placeholder": "Inicio de clase: "}),
            'hora_fin':forms.TextInput(attrs={"placeholder": "fin de la clase: "}),
          }
          labels = {
               'courses_name' : _(''),
               'courses_description': _(''),
               'hora_ini': _(''),
               'hora_fin': _(''),
          }

     def clean(self):
           cleaned_data = super(NewCoursesform, self).clean()
           self.name = cleaned_data.get("name")
           self.description = cleaned_data.get("description")
           self.hora_ini = cleaned_data.get("hora_ini")
           self.hora_fin = cleaned_data.get("hora_fin")
           return cleaned_data

class SearcherForm(forms.Form):
     searchfield = forms.CharField(max_length=90, widget=forms.TextInput(attrs={'placeholder': 'Search'}), label='')



class MessageForm(ModelForm):
     class Meta:
          model = Teachers_message
          fields = "__all__"
          exclude = ['users']
          labels = {
               'receiver' : _(''),
               'asunto': _(''),
               'content': _(''),
          }
          widgets = {
            'receiver':forms.TextInput(attrs={"placeholder": "Para: "}),
            'asunto': forms.TextInput(attrs={"placeholder": "asunto: "})
          }
     def clean(self):
           cleaned_data = super(MessageForm, self).clean()
           self.receiver = cleaned_data.get("title")
           self.asunto = cleaned_data.get("content")
           self.content = cleaned_data.get("receiver")
           return cleaned_data


class Homeworkform(ModelForm):
     class Meta:
          model = Teachers_homework
          fields = "__all__"
          exclude = ['users']
          widgets = {
             'homework_description': Textarea(attrs={'cols': 40, 'rows': 6, 'placeholder': 'Ingrese una descripción aquí...'}),
             'title':forms.TextInput(attrs={"placeholder": "Ingrese el título de la tarea"}),
             'first_question': forms.TextInput(attrs={"placeholder": "Ingrese la primera pregunta"}),
             'secound_question': forms.TextInput(attrs={"placeholder": "Ingrese la segunda pregunta"}),
             'third_question': forms.TextInput(attrs={"placeholder": "Ingrese la tercera pregunta"}),
             'fourth_question': forms.TextInput(attrs={"placeholder": "Ingrese la cuarta pregunta"}),
             'fifth_question': forms.TextInput(attrs={"placeholder": "Ingrese la quinta pregunta"}), 
          }
          
          labels = {
               'homework_title' : _(''),
               'homework_description': _(''),
               'first_question': _(''),
               'secound_question': _(''),
               'third_question': _(''),
               'fourth_question': _(''),
               'fifth_question': _(''),
          }

     def clean(self):
           cleaned_data = super(Homeworkform, self).clean()
           self.title = cleaned_data.get("title")
           self.homework_description = cleaned_data.get("homework_description")
           self.archive = cleaned_data.get("archive")
           return cleaned_data

class  PostContentForm(ModelForm):
    class Meta:
        model =  PostContent
        fields = ['content']
        exclude = ['fecha', 'hora_post']
        
        widgets = {
           'content': Textarea(attrs={'cols': 60, 'rows': 6, 'placeholder': 'crea una publicacion...'}),
        }
     
        labels = {
          'content': ''
        }
        
    def clean(self):
        cleaned_data = super(PostContentForm, self).clean()
        self.content = cleaned_data.get("content")
        self.fecha = cleaned_data.get("fecha")
        self.hora_post = cleaned_data.get("hora_post")
        
        if len(self.content) < 10:
            raise ValidationError('El contenido debe tener al menos 10 caracteres')
        return cleaned_data

profesores/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from .forms import *
from rest_framework.views import APIView
from .models import *
from principal.forms import Signup
import datetime
from rest_framework.response import Response
from .serializers import Teachers_homeworkSerializer
from rest_framework import status
from django.http import Http404
from  tools.videoCapturing  import VIDEOCAPTURE 


# Create your views here.

class PerfilView(View):
    template_name = 'perfil.html'
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
           print(request.POST['search_field'])
        return render(request, self.template_name)

class HomeView(ListView):
    template_name = 'teachers_home.html'
    form_class = [SearcherForm, PostContentForm, ImageLoad]
    model = PostContent
    object_list = PostContent.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form1'] = self.form_class[0]()
        context['form2'] = self.form_class[1]()
        return context

    def get(self, request, *args, **kwags):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        form1 = context['form1']
        form2 = context['form2']
        if form1.is_valid():
            print('form1 is valid')
        else:
            print('form1 not valid')
        if  form2.is_valid():
           new_post = PostContent(
               content = form2.content,
               fecha = form2.fecha,
               hora_post = form2.hora_post,
           )
        
           print('esto es un post', new_post.content, 'esto es la hora', new_post.hora_post)
          
        else:
            print('form2 is not valid')
        return render(request, self.template_name,context)


class FriendsView(View):
     template_name = 'teachers_friends.html'

     def get(self, request, *args, **kwargs):
         return render(request, self.template_name)



class DeskView(View):
     template_name = 'desk.html'
     form_class = [
           NewCoursesform, 
           Homeworkform,
           SearcherForm,
     ]

     def get(self, request, *args, **kwargs):
         form1 = self.form_class[0]()
         form2 = self.form_class[1]()
         form3 = self.form_class[2]()
         return render(request, self.template_name, {'form1':form1, 'form2':form2, 'form3':form3})
    #esto es un metodo post que maneja las peticiones post         
     def post(self, request, *args, **kwargs):
         form1 = self.form_class[0](request.POST)
         form2 = self.form_class[1](request.POST)
         form3 = self.form_class[2](request.POST)
         if form1.is_valid() and form1.is_bound:
               #this conditional tries to create new course
               new_class =  Courses(
                     courses_name = form1.cleaned_data['courses_name'],
                     courses_description = form1.cleaned_data['courses_description'],
                     miniatura = form1.cleaned_data['miniatura'],
                     hora_ini = form1.cleaned_data['hora_ini'],
                     hora_fin = form1.cleaned_data['hora_fin'], 
               )
               print(new_class.courses_description)
         else:
            print('form1 is not valid')
         if form2.is_valid() and form2.is_bound:
               #this conditional tries to create a new homework
               new_homework = Teachers_homework(
                   homework_title = form2.cleaned_data['homework_title'],
                   homework_description = form2.cleaned_data['homework_description'],
                   first_question = form2.cleaned_data['first_question'],
                   secound_question = form2.cleaned_data['secound_question'],
                   third_question = form2.cleaned_data['third_question'],
                   fourth_question = form2.cleaned_data['fourth_question'],
                   fifth_question = form2.cleaned_data['fifth_question'],
               )
             
               new_homework.save()
               obj = Teachers_homework.objects.all
               print(obj)

         else:
           # Don't validate form2 if it is not bound
           pass
         
         return render(request, self.template_name, {'form1': form1, 'form2':form2, 'form3':form3})


class NewHomeworkView(View):
    form_class = [SearcherForm, Homeworkform]
    template_name = 'homework.html'
    
    def get(self, request):
        form = self.form_class[0]()
        form2 = self.form_class[1]()
        return render(request, self.template_name, {'form':form, 'form2':form2})

    def post(self, request):
        form = self.form_class[0](request.POST)
        form2 = self.form_class[1](request.POST)
        return render(request, self.template_name, {'form':form, 'form2':form2})


class MessagesView(View):
     form_class = MessageForm
     template_name = "message.html"

     def get(self, request, *args, **kwargs):
         form = self.form_class()
         return render(request, self.template_name, {'form':form})
     
     def post(self, request, *args, **kwargs):
         form = self.form_class(request.POST)
         if form.is_valid():
            mssg = Mensajes(
                receiver = form.reciver,
                asunto = form.asunto,
                content = form.content,
            )
            mssg.save()
            
         
         return render(request, self.template_name, {'form':form})

class LiveView(TemplateView):
     template_name = 'liveclass.html'
     videolive = VIDEOCAPTURE(0)
     processing = videolive.capturingProcess

     def get(self, request):
        context = {
          'vid':self.processing()
        }
        return render(request, self.template_name, context)
     
     def post(self, request):
        return render(request, self.template_name)

profesores/templates/desk.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/desk.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@300&display=swap" rel="stylesheet">
    <script src="{% static 'javascript/desk.js' %}"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <title>Document</title>
</head>
<body>
   <div id="general_box">
      <header>
         <h1 id="title">TutorLink</h1>
         <div id="picture" id="user-img" onclick="accountpanel()"></div>
         <div id="search_block">
            <form method="POST" id="search_form">
                 {% csrf_token %}
                 <button id="search_btn">
                  <span class="material-symbols-outlined">search</span>
                 </button>
                 {{ form3 }}
            </form>
         </div>
      </header>
      <div id="root_container">
         <div id="left_column">
            <ul id="menu_feature">
               <li class="parts">
                  <a href="{% url  'profesores:teachers_home'%}" class="hyperlink"> <span class="material-symbols-sharp">home</span>Inicio</a>
               </li>
               <li class="parts">
                  <a href="{% url 'profesores:teachers_messages' %}" class="hyperlink"> <span class="material-symbols-sharp">chat</span>Inbox</a>
               </li>
               <li class="parts">
                  <a href="{% url 'profesores:desktop' %}" class="hyperlink"><span class="material-symbols-sharp">work</span>workshop</a>
               </li>

               <li class="parts">
                  <a href="{% url  'profesores:co-workers' %}" class="hyperlink"><span class="material-symbols-sharp">group</span>Friends</a>
               </li>
               <li class="parts">

                  <p class="hyperlink"><span class="material-symbols-sharp">notifications</span>Notificaciones</p>
               </li>
               <li class="parts">
                  <a href="{% url 'profesores:teacher_perfil' %}" class="hyperlink"><span class="material-symbols-sharp">person</span>Perfil</a>
               </li>
               <li class="parts" onclick="menu_hidden">
                  <p class="hyperlink"> <span class="material-symbols-sharp">more_vert</span>Mas</a>
               </li>
            </ul>
        </div>
        <div id="central_content">
               <div id="folderholder">
                   <div class="folders" id="folder1">
                      <span class="folders-name">Incoming Homeworks</span>
                   </div>
                   <div class="folders" id="folder2">
                       <span class="folders-name">Incoming tests</span>
                   </div>
                   <div class="folders" id="folder3">
                       <span class="folders-name">borrador</span>
                   </div>
               </div>
               <div id="content">
                <p>where im</p>
               </div>
           </div>

           <div id="right_column">
               <ul id="work_tools">
                  <li class="work"  id="newlesson" onclick="Openit()">
                        <p id="create" class="mssgtools">Nueva Leccion</p>
                  </li>
                  <li class="work" id="new_file"  onclick="slider()">
                     <span id="courses" class="mssgtools">Tus-Cursos</span>
                  </li>
               </ul>
               <div id="calender">
                  <h3 id="agenda">Tu-agenda</h3>

               </div>
           </div>
         <div id="courses_container">
            <button id="created_btn">
                <span id="new_course" onclick="create()">Crear clase</span>
            </button>
            <div id="courses_list">
                <p>no tienes ninguna clase todavia</p>
            </div>
        </div>
 
        <div id="form_block">
            <form method="POST" id="id_form1" enctype="multipart/form-data">
                {%csrf_token %}
                <span class="material-symbols-sharp" id="close1" onclick="closefunction()">close</span>
                {{ form1.courses_name }}
                {{ form1.courses_description }}
                {{ form1.miniatura }}
                <div id="time">
                  {{ form1.hora_ini }}
                  {{ form1.hora_fin }}
                </div>
                <input type="submit" name="making_button" id="crear" value="Crear">
            </form>
        </div>

      <div id="modal_block">
         <form method="POST" id="id_form2" enctype="multipart/form-data">
             {% csrf_token %}
             <span class="material-symbols-sharp" id="close2" onclick="Closefunction()">close</span>
             {{ form2.homework_title }}
             {{ form2.homework_description }}
             {{ form2.first_question }}
             {{form2.secound_question }}
             {{ form2.third_question }}
             {{form2.fourth_question }}
             {{ form2.fifth_question }}
             <div id="form-tools">
              {{ form2.font_size }}
              {{ form2.form_type }}
            </div>
             <input type="submit" name="making_button" id="crear" value="Crear">

         </form>
      </div>
       
   </div>
   <div id="select_lesson">
      <span class="material-symbols-sharp" id="closetag" onclick="Close()">close</span>
      <ul id="lessons_options">
         <li class="lessons" id="option1">
            <span class="lessons-type">
                NewLessonLive
            </span>
         </li>
         <li class="lessons" id="option2">
            <span class="lessons-type">
                NewLesson
            </span>
         </li>
      </ul>
   </div>
   <div id="accounts_manager">
      <div id="account_data">
          <div id="picture_account">

          </div>
          <h3>{{ user.username }}</h3>
          <h3>{{user.email}}</h3>
      </div>
      <div id="accounts">
          {% if user.is_authenticated %}
            <a href="#" class="manager">Log-out</a>
            {% else %}
            <a href="{% url 'login' %}" class="manager">Log-In</a>
         {% endif %}
         <a href="" id="change_account" class="manager">Cambiar cuenta</a>
         <a href="" id="salir" class="manager">Salir de todas las cuentas</a>
      </div>
      <ul id="settings">
            <li class="configurations" id="conf">
               <a href="{% url 'estudiantes:configurations' %}" class="set_configuration">Configuracion</a>
            </li>
            <li class="configurations" id="saved">
               <a href="" class="set_configuration">Guardadas</a>
            </li>
            <li class="configurations" id="activity">
               <a href="" class="set_configuration">Tu actividad</a>
            </li>
            <li class="configurations" id="problem">
               <a href="" class="set_configuration">Informar de un problema</a>
            </li>
            <li class="configurations" id="changelook" onclick="Night()">
               <p class="set_configuration">Cambiar Aspecto</p>
            </li>
      </ul>
  </div>
</div>
</body>
</html>

profesores/templates/homework.html
{% extends 'base/homework-maker.html' %}

profesores/templates/liveclass.html
{% extends 'base/base_liveclass.html' %}

profesores/templates/message.html
{% extends 'base/message.html' %}

profesores/templates/perfil.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/tpublic.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bitter:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>Document</title>
</head>
<body>
    <div id="general_box">
        <header>
            <h1 id="title"><a href="{% url 'profesores:teachers_home' %}" id="url_title">TutorLink</a></h1>
            <div id="picture"></div>
            <div id="search_block">
               <form method="POST" id="search_form">
                    {% csrf_token %}
                    <button id="search_btn">
                      <span class="material-symbols-outlined">search</span>
                     </button>
                     {{ form1.searchfield }}
               </form>
            </div>
        </header>
        <div id="root_content">
            
            <div id="data">
                <div id="user_info">
                    <div id="user-img">

                    </div>
                    <div id="user-data">
                        <h3>Username Example</h3>
                        <h3>User city</h3>
                    </div>
                    <div id="data-user">
                        <input type="button" value="Follow">
                        <input type="button" value="Message">
                    </div>
                </div>
                <div id="user_content">
                    <h1 id="title-course">Cursos:</h1>
                    <ul id="horizontal_menu">
                       <li class="h_parts"  id="homework">
                          <p class="info" id="id_homework">Tareas</p>
                       </li>
                       <li class="h_parts" id="test">
                          <p class="info" id="id_test">Examenes</p>
                       </li>
                       <li class="h_parts" id="notes">
                          <p class="info" id="id_notes">Red-list</p>
                       </li>
                    </ul>
                </div>
                <div id="friends">
                    <h2 id="friend">Amigos</h2>
                </div>
            </div>
            <div id="user-metric">

            </div>
        </div>
    </div>
</body>
</html>

profesores/templates/teachers_friends.html
{% extends 'base/base_friends.html' %}

{% block friends %}
<div id="root_content">
        <div id="menu_options">
            <div class="tools" id="search_tool">
                <form method="POST" id="modular_form">
                    <input type="search" name="searcher" id="seacrh_field" placeholder="Buscar">
                    <input type="submit" name='bimiting' id="searcher_button" value="Buscar">
                </form>
            </div>
            <div id="add_tool" class="tools">
               <p>agregar</p>
            </div>
            
            <div class="tools" id="delete_tool">
                   <p>Borrar</p>
            </div>
        </div>
        <div id="amigos">

        </div>
</div>
{% endblock %}

profesores/templates/teachers_home.html
{% extends 'base/base_file1.html' %}

{% block user_info %}
<div id="info">
    <p id="users_name">{{ user.username }}</p>
    <h4 id="moreinfo">courses</h4>
</div>
{% endblock %}